# Generated by Django 5.2.5 on 2025-10-03 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeId', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('catch_copy', models.TextField(blank=True, null=True)),
                ('foodImageUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('recipeUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('recipeCost', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredients', models.JSONField(default=list)),
                ('instructions', models.JSONField(default=list)),
                ('recommendation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'unique_together': {('user', 'recipeId')},
            },
        ),
    ]
