# Generated by Django 5.2.5 on 2025-10-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='cooking_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='main_nutrients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
